# tab-separated file of the samples
samples: samples.tsv

# pipeline file locations
result_dir: ./results  # where to store results
genome_dir: ./genomes  # where to look for or download the genomes
# fastq_dir: ./results/fastq  # where to look for or download the fastqs


# contact info for multiqc report and trackhub
email: yourmail@here.com

# produce a UCSC trackhub?
create_trackhub: True

# how to handle replicates
biological_replicates: fisher  # change to "keep" to not combine them
technical_replicates: merge    # change to "keep" to not combine them

# which aligner to use
aligner: bwa-mem

# filtering after alignment
remove_blacklist: True
remove_mito: True
tn5_shift: True
min_mapping_quality: 30
only_primary_align: True

# peak callers (supported peak callers are macs2, and genrich)
peak_caller:
  macs2:
      --shift -100 --extsize 200 --nomodel --keep-dup 1 --buffer-size 10000
#  genrich:
#      -y -j -r


#### differential gene expression analysis (optional) #####

# specify contrasts to perform analysis
diffexp:
  deseq2:
    DE_params:
      multiple_testing_procedure: BH  # options: BH/IHW
      alpha_value: 0.05
      shrinkage_estimator: apeglm
    contrasts:
      - 'stage_2_1'
      - 'stage_all_1'
